<?php

return [
    'roles' => [
        'owner' => 'Pemilik',
        'admin' => 'Admin',
        'manager' => 'Manajer',
        'cashier' => 'Kasir',
        'inventory' => 'Staf Inventory',
        'accountant' => 'Akuntansi',
        'waiter' => 'Pelayan',
        'void_actor' => 'Pelaksana Void',
        'void_approver' => 'Penyetuju Void',
        'inventory_viewer' => 'Inventory (Lihat Saja)',
        'purchase_viewer' => 'Pembelian (Lihat Saja)',
        'purchase_creator' => 'Pembelian (Buat)',
        'purchase_receiver' => 'Pembelian (Terima)',
        'opname_creator' => 'Stock Opname (Buat)',
        'opname_viewer' => 'Stock Opname (Lihat Saja)',
        'movement_creator' => 'Pergerakan Stok (Buat)',
        'pos_only' => 'POS Saja',
        'transactions_only' => 'Transaksi Saja',
        'no_access' => 'Tanpa Akses',
    ],

    'permission_groups' => [
        'dashboard' => 'Dashboard',
        'pos' => 'Kasir (POS)',
        'products' => 'Produk',
        'categories' => 'Kategori',
        'dining_tables' => 'Meja & QR Code',
        'transactions' => 'Transaksi',
        'members' => 'Member',
        'reports' => 'Laporan',
        'guides' => 'Buku Panduan',
        'vouchers' => 'Voucher',
        'discounts' => 'Diskon',
        'inventory' => 'Inventory',
        'users' => 'Pengguna',
        'roles' => 'Peran & Hak Akses',
        'settings' => 'Pengaturan',
    ],

    'permissions' => [
        'dashboard.access' => 'Akses Dashboard',

        'pos.access' => 'Akses POS',

        'guides.view' => 'Buku Panduan',

        'products.view' => 'Lihat Produk',
        'products.create' => 'Tambah Produk',
        'products.edit' => 'Ubah Produk',
        'products.delete' => 'Hapus Produk',

        'categories.view' => 'Lihat Kategori',
        'categories.create' => 'Tambah Kategori',
        'categories.edit' => 'Ubah Kategori',
        'categories.delete' => 'Hapus Kategori',

        'dining_tables.view' => 'Lihat Meja & QR Code',
        'dining_tables.edit' => 'Kelola Meja & QR Code',

        'transactions.view' => 'Lihat Transaksi',
        'transactions.details' => 'Lihat Detail Transaksi',
        'transactions.pii.view' => 'Lihat Data Pelanggan',
        'transactions.print' => 'Cetak Struk Transaksi',
        'transactions.void' => 'Void Transaksi',
        'transactions.refund' => 'Refund Transaksi',
        'transactions.void.approve' => 'Setujui Void Transaksi',
        'transactions.refund.approve' => 'Setujui Refund Transaksi',

        'members.view' => 'Lihat Member',
        'members.create' => 'Tambah Member',
        'members.edit' => 'Ubah Member',
        'members.delete' => 'Hapus Member',
        'members.pii.view' => 'Lihat Data Member',
        'members.regions.view' => 'Lihat Wilayah Member',
        'members.regions.manage' => 'Kelola Wilayah Member',

        'reports.view' => 'Akses Laporan',
        'reports.sales' => 'Laporan Penjualan',
        'reports.performance' => 'Laporan Performa',
        'reports.expenses.manage' => 'Kelola Beban Operasional',

        'vouchers.view' => 'Lihat Voucher',
        'vouchers.manage' => 'Kelola Voucher',

        'discounts.manual.apply' => 'Diskon Manual',

        'inventory.view' => 'Lihat Inventory',
        'inventory.manage' => 'Kelola Inventory',
        'inventory.ingredients.view' => 'Lihat Bahan Baku',
        'inventory.ingredients.manage' => 'Kelola Bahan Baku',
        'inventory.suppliers.view' => 'Lihat Supplier',
        'inventory.suppliers.manage' => 'Kelola Supplier',
        'inventory.movements.view' => 'Lihat Pergerakan Stok',
        'inventory.movements.manage' => 'Kelola Pergerakan Stok',
        'inventory.movements.create' => 'Tambah Pergerakan Stok',
        'inventory.movements.delete' => 'Hapus Pergerakan Stok',
        'inventory.purchases.view' => 'Lihat Pembelian',
        'inventory.purchases.manage' => 'Kelola Pembelian',
        'inventory.purchases.create' => 'Buat Pembelian',
        'inventory.purchases.edit' => 'Ubah Pembelian',
        'inventory.purchases.receive' => 'Terima Pembelian',
        'inventory.purchases.cancel' => 'Batalkan Pembelian',
        'inventory.opnames.view' => 'Lihat Stock Opname',
        'inventory.opnames.manage' => 'Kelola Stock Opname',
        'inventory.opnames.create' => 'Buat Stock Opname',
        'inventory.opnames.edit' => 'Ubah Stock Opname',
        'inventory.opnames.refresh_system_stocks' => 'Refresh Stok Sistem',
        'inventory.opnames.post' => 'Posting Stock Opname',
        'inventory.opnames.cancel' => 'Batalkan Stock Opname',
        'inventory.reports.view' => 'Akses Laporan Inventory',

        'users.view' => 'Lihat Pengguna',
        'users.create' => 'Tambah Pengguna',
        'users.edit' => 'Ubah Pengguna',
        'users.delete' => 'Hapus Pengguna',

        'roles.view' => 'Lihat Peran',
        'roles.manage' => 'Kelola Peran',

        'settings.view' => 'Lihat Pengaturan',
        'settings.edit' => 'Ubah Pengaturan',
        'settings.store.view' => 'Lihat Pengaturan Toko',
        'settings.store.edit' => 'Ubah Pengaturan Toko',
        'settings.printers.view' => 'Lihat Pengaturan Printer',
        'settings.printers.edit' => 'Ubah Pengaturan Printer',
        'settings.system.view' => 'Lihat Pengaturan Sistem',
        'settings.system.edit' => 'Ubah Pengaturan Sistem',
        'settings.points.view' => 'Lihat Pengaturan Poin',
        'settings.points.edit' => 'Ubah Pengaturan Poin',
        'settings.targets.view' => 'Lihat Target Bulanan',
        'settings.targets.edit' => 'Ubah Target Bulanan',
    ],
];
